---
# You can override vars by using host or group vars

###########
# GENERAL #
###########
copy_admin_key: true
# Whether or not to generate secure certificate to iSCSI gateway nodes
generate_crt: False

configure_iscsi_clients: False

iscsi_pool_name: rbd
iscsi_pool_size: "{{ osd_pool_default_size }}"

##################
# RBD-TARGET-API #
##################
# Optional settings related to the CLI/API service
api_user: admin
api_password: admin
api_port: 5000
api_secure: false
loop_delay: 1
trusted_ip_list:


