---
- name: install ceph-mgr package on RedHat or SUSE
  package:
    name: ceph-mgr
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  register: result
  until: result is succeeded
  when:
    - ansible_os_family in ['RedHat', 'Suse']

- name: install ceph-mgr-dashboard package on RedHat or SUSE
  package:
    name: ceph-mgr-dashboard
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  register: result
  until: result is succeeded
  when:
    - ansible_os_family in ['RedHat', 'Suse']
    - ceph_dashboard

- name: install ceph-mgr-diskprediction local package on RedHat or SUSE
  package:
    name: ceph-mgr-diskprediction-{{ diskprediction_mode }}
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  register: result
  until: result is succeeded
  when:
    - ansible_os_family in ['RedHat', 'Suse']
    - ceph_diskprediction

- name: install ceph mgr for debian
  apt:
    name: ceph-mgr
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
    default_release: "{{ ceph_stable_release_uca | default('') }}{{ ansible_distribution_release ~ '-backports' if ceph_origin == 'distro' and ceph_use_distro_backports else '' }}"
  register: result
  until: result is succeeded
  when:
    - ansible_os_family == 'Debian'
