---
- hosts: osds
  tasks:
    - name: execute generate-osd-vars script
      command: /usr/bin/sh /opt/tools/generate-osd-vars.sh
      register: output

    - debug:
         msg: "{{ output.stdout }}"

    - local_action: copy content={{ output.stdout }} dest=/usr/share/ceph-ansible/host_vars/{{ ansible_hostname }}.yml
