- hosts: mdss
  gather_facts: false
  become: True
  any_errors_fatal: true
  pre_tasks:
    - name: set ceph mds install 'In Progress'
      run_once: true
      set_stats:
        data:
          installer_phase_ceph_mds:
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

  tasks:
    - import_role:
        name: ceph-defaults
      tags: ['ceph_update_config']
    - import_role:
        name: ceph-facts
      tags: ['ceph_update_config']
    - import_role:
        name: ceph-handler
    - import_role:
        name: ceph-common
    - import_role:
        name: ceph-config
      tags: ['ceph_update_config']
    - import_role:
        name: ceph-mds

  post_tasks:
    - name: set ceph mds install 'Complete'
      run_once: true
      set_stats:
        data:
          installer_phase_ceph_mds:
            status: "Complete"
            end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"


- hosts: rgws
  gather_facts: false
  become: True
  any_errors_fatal: true
  pre_tasks:
    - name: set ceph rgw install 'In Progress'
      run_once: true
      set_stats:
        data:
          installer_phase_ceph_rgw:
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

  tasks:
    - import_role:
        name: ceph-defaults
      tags: ['ceph_update_config']
    - import_role:
        name: ceph-facts
      tags: ['ceph_update_config']
    - import_role:
        name: ceph-handler
    - import_role:
        name: ceph-common
    - import_role:
        name: ceph-config
      tags: ['ceph_update_config']
    - import_role:
        name: ceph-rgw

  post_tasks:
    - name: set ceph rgw install 'Complete'
      run_once: true
      set_stats:
        data:
          installer_phase_ceph_rgw:
            status: "Complete"
            end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
            
- hosts: mons
  gather_facts: false
  become: True
  any_errors_fatal: true
  tasks:
    - import_role:
        name: ceph-defaults
    - name: get ceph status from the first monitor
      command: ceph --cluster {{ cluster }} -s
      register: ceph_status
      changed_when: false
      delegate_to: "{{ groups[mon_group_name][0] }}"
      run_once: true

    - name: "show ceph status for cluster {{ cluster }}"
      debug:
        msg: "{{ ceph_status.stdout_lines }}"
      delegate_to: "{{ groups[mon_group_name][0] }}"
      run_once: true
      when: not ceph_status.failed

