---
- hosts:
  - smbs

  gather_facts: false
  any_errors_fatal: true
  become: true

  tags:
    - always

  vars:
    delegate_facts_host: True

  pre_tasks:

    - import_tasks: raw_install_python.yml

    - name: gather facts
      setup:
      when:
        - not delegate_facts_host | bool

    - name: gather and delegate facts
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      with_items: "{{ groups['all'] }}"
      run_once: true
      when:
        - delegate_facts_host | bool

    - name: install required packages for fedora > 23
      raw: sudo dnf -y install python2-dnf libselinux-python ntp
      register: result
      when:
        - ansible_distribution == 'Fedora'
        - ansible_distribution_major_version|int >= 23
      until: result is succeeded

    - name: check if it is atomic host
      stat:
        path: /run/ostree-booted
      register: stat_ostree
      tags:
        - always

    - name: set_fact is_atomic
      set_fact:
        is_atomic: '{{ stat_ostree.stat.exists }}'
      tags:
        - always

  tasks:
    - import_role:
        name: ceph-defaults
    - import_role:
        name: ceph-facts
    - import_role:
        name: ceph-validate
    - import_role:
        name: ceph-infra

- hosts: smbs
  gather_facts: false
  become: True
  any_errors_fatal: true
  serial: 1
  pre_tasks:
    - name: set ceph client install 'In Progress'
      run_once: true
      set_stats:
        data:
          installer_phase_ceph_client:
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

  tasks:
    - import_role:
        name: ceph-defaults
      tags: ['ceph_update_config']
    - import_role:
        name: ceph-facts
      tags: ['ceph_update_config']
    - import_role:
        name: ceph-common
    - import_role:
        name: ceph-samba

  post_tasks:
    - name: set ceph samba install 'Complete'
      run_once: true
      set_stats:
        data:
          installer_phase_ceph_client:
            status: "Complete"
            end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- hosts: smbs
  gather_facts: false
  become: True
  any_errors_fatal: true
  tasks:
    - import_role:
        name: ceph-defaults
    - name: wait for CTDB to go healthy
      run_once: true
      wait_for:
        delay: 30  #we wait enough time for ctdb to recover and start hosting VIP
        timeout: 0
    - name: get ctdb status from the first node
      command: ctdb status
      register: ctdb_status
      changed_when: false
      delegate_to: "{{ groups[smb_group_name][0] }}"
      run_once: true
    - name: "show ctdb status for cluster {{ cluster }}"
      debug:
        msg: "{{ ctdb_status.stdout_lines }}"
      delegate_to: "{{ groups[smb_group_name][0] }}"
      run_once: true
      when: not ctdb_status.failed