---
- name: Get admin keyring for rados locking
  command: "ceph auth get client.admin"
  register: admin_keyring
  delegate_to: "{{ groups[mon_group_name][0] }}"
  changed_when: false
  when:
    - cephx|bool

- name: Write admin keyring for rados locking
  copy:
    content: "{{ admin_keyring.stdout }}"
    dest: "/etc/ceph/{{cluster}}.client.admin.keyring"
    force: yes
    group: ceph
    owner: ceph
    mode: 0600
  when:
    - cephx|bool
