---
- name: set_fact docker_exec_cmd_nfs
  set_fact:
    docker_exec_cmd_nfs: "{{ container_binary }} exec ceph-mon-{{ hostvars[groups[mon_group_name][0]]['ansible_hostname'] }}"
  when:
    - containerized_deployment

#### GENERATE CONF
- name: create /etc/ganesha
  file:
    path: /etc/ganesha
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: generate ganesha configuration file
  action: config_template
  args:
    src: "ganesha.conf.j2"
    dest: /etc/ganesha/ganesha.conf
    owner: "root"
    group: "root"
    mode: "0644"
    config_type: ini
  notify:
    - restart ceph nfss
###### GENERATE CONF

###### CREATE GRACE DB
- name: check if rados rados grace db object exists
  shell: "{{ docker_exec_cmd_nfs | default('') }} rados -p {{ cephfs_metadata }} -n {{ ceph_nfs_rados_grace }} --cluster {{ cluster }} ls | grep grace/"
  changed_when: false
  failed_when: false
  register: rados_grace_exists
  check_mode: no
  when:
    - ceph_nfs_rados_backend
  delegate_to: "{{ groups[mon_group_name][0] }}"
  run_once: true
- name: initialize ganesha rados grace database
  command: "{{ docker_exec_cmd_nfs | default('') }} ganesha-rados-grace -p {{ cephfs_metadata }} -n {{ ceph_nfs_rados_grace }} add {{ ansible-hostname }}"
  when:
    - ceph_nfs_rados_backend
    - ceph_nfs_rados_backed_mode == 'rados_cluster'
    - rados_grace_exists.rc != 0
######## CREATE GRACE DB

##### CREATE EXPORT INDEX OBJECTS
- name: check if rados export index object exists
  shell: "{{ docker_exec_cmd_nfs | default('') }} rados -p {{ cephfs_metadata }} -N {{ ceph_nfs_rados_export_index }} --cluster {{ cluster }} ls|grep conf-{{ ansible-hostname }}/"
  changed_when: false
  failed_when: false
  register: rados_index_exists
  check_mode: no
  when:
    - ceph_nfs_rados_backend
  delegate_to: "{{ groups[mon_group_name][0] }}"
  run_once: true
- name: create an empty rados export index object
  command: "{{ docker_exec_cmd_nfs | default('') }} rados -p {{ cephfs_metadata }} -N {{ ceph_nfs_rados_export_index }} --cluster {{ cluster }} put conf-{{ ansible_hostname }} /dev/null"
  when:
    - ceph_nfs_rados_backend
    - rados_index_exists.rc != 0
  delegate_to: "{{ groups[mon_group_name][0] }}"
  run_once: true
####### CREATE EXPORT INDEX OBJECTS

- name: generate systemd unit file
  become: true
  template:
    src: "{{ role_path }}/templates/ceph-nfs.service.j2"
    dest: /etc/systemd/system/ceph-nfs@.service
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - containerized_deployment
  notify:
    - restart ceph nfss

- name: systemd start nfs container
  systemd:
    name: ceph-nfs@{{ ceph_nfs_service_suffix | default(ansible_hostname) }}
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
  when:
    - containerized_deployment
    - ceph_nfs_enable_service

- name: start nfs gateway service
  systemd:
    name: nfs-ganesha
    state: started
    enabled: yes
    masked: no
  when:
    - not containerized_deployment
    - ceph_nfs_enable_service
