---
galaxy_info:
  author: Brett Kelly
  description: Config Samba & CTDB
  license: Apache
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
  categories:
    - system
dependencies: []
