---
- name: 45Drives Repository - Configure 45drives repository
  yum_repository:
    name: ceph_45drives
    description: 45Drives $basearch repo
    gpgcheck: no
    enabled: yes
    state: present
    baseurl: "{{ ceph_45drives_repo_url }}"
    file: ceph_45drives
    priority: "1"
  register: result
  until: result is success

- name: install prometheus
  package:
    name: "{{ item }}"
    state: present
  register: result
  until: result is succeeded
  with_items:
    - prometheus2
    - alertmanager

- name: start prometheus services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  failed_when: false
  with_items:
    - prometheus
    - alertmanager