---
- name: include common.yml
  include_tasks: common.yml

- name: include prerequisites.yml
  include_tasks: prerequisites.yml

# deploy_ssl_keys used the ansible controller to create self-signed crt/key/pub files
# and transfers them to /etc/ceph directory on each controller. SSL certs are used by
# the API for https support.
- name: include deploy_ssl_keys.yml
  include_tasks: deploy_ssl_keys.yml
  when: generate_crt | bool

- name: include postrequisites.yml
  include_tasks: postrequisites.yml