---
- name: config_cephfs | Create local cephx users
  ceph_key:
    name: "{{ item.name }}"
    state: present
    caps: "{{ item.caps }}"
    cluster: "{{ cluster }}"
    secret: "{{ item.key | default('') }}"
  with_items: "{{ cephfs_keyring }}"
  delegate_to: "{{ groups[mon_group_name][0] }}"
