---
- name: include pre_requisite.yml
  include_tasks: pre_requisite.yml

- name: include create_users_keys.yml
  include_tasks: create_users_keys.yml
  when: user_config | bool

- name: include mount_shares.yml
  include_tasks: mount_shares.yml
  when: mount_cephfs_on_clients | bool  
