---
# samba_repo can either be '45drives' or 'community'.
# Community will install Samba,CTDB & Winbind packages from the standard CentOS repo.
# 45drives will install the same packages and version of Samba,CTDB & Winbind as communuty but rebuilt with support for storing CTDB locks in RADOS objects.
# Default is to install with RADOS support. If not using samba with CephFS then "community" is fine.
samba_repo: 45drives
samba_45drives_repo_url: "http://images.45drives.com/ceph/samba/repo"

# Update samba packages if already installed
upgrade_samba_packages: true

# Roles
samba_server: true
samba_cluster: true
domain_member: true