---
- name: config_ctdb | configuring ctdb service
  template:
    src: "etc/ctdb/ctdb.conf.j2"
    dest: "/etc/ctdb/ctdbd.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ctdb

- name: config_ctdb | configuring ctdb public_addresses
  template:
    src: "etc/ctdb/public_addresses.j2"
    dest: "{{ ctdb_public_addresses_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ctdb

- name: config_ctdb | configuring ctdb nodes
  template:
    src: "etc/ctdb/nodes.j2"
    dest: "/etc/ctdb/nodes"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ctdb