---
- name: config_ctdb | configuring ctdb service
  template:
    src: "etc/ctdb/ctdb.conf.j2"
    dest: "/etc/ctdb/ctdb.conf"
    owner: root
    group: root
    mode: 0644

- name: config_ctdb | configuring ctdb public_addresses
  template:
    src: "etc/ctdb/public_addresses.j2"
    dest: "/etc/ctdb/public_addresses"
    owner: root
    group: root
    mode: 0644

- name: config_ctdb | configuring ctdb nodes
  template:
    src: "etc/ctdb/nodes.j2"
    dest: "/etc/ctdb/nodes"
    owner: root
    group: root
    mode: 0644

- name: config_ctdb | configuring ctdb tunables
  template:
    src: "etc/ctdb/ctdb.tunables.j2"
    dest: "/etc/ctdb/ctdb.tunables"
    owner: root
    group: root
    mode: 0644

- name: config_ctdb | create ctdb volatile directory
  file:
      path: /var/lib/ctdb/volatile
      state: directory
      mode: '0755'

- name: config_ctdb | link core ctdb event scripts
  file:
    src: '/usr/share/ctdb/events/legacy/{{ item.src }}'
    dest: /etc/ctdb/events/legacy/
    state: link
  with_items:
    - 00.ctdb.script
    - 10.interface.script

