---
- name: join_domain | checking if already joined to domain
  stat:
    path: "{{ shared_storage_mountpoint }}/fsgw/.domain_joined"
  register: "domain_joined_check"

- name: join_domain | restarting ctdb (if not joined to domain)
  service:
    name: "ctdb"
    state: restarted
  register: "ctdb_restarted"
  when: not domain_joined_check.stat.exists

- name: join_domain | waiting for ctdb to restart
  wait_for:
    delay: 60  #we wait enough time for ctdb to startup samba services in order to join domain
    host: "{{ ansible_default_ipv4.address }}"
    port: 4379
  when: ctdb_restarted.changed

- name: join_domain | joining domain
  shell: net ads join -U "{{ active_directory_info.domain_join_user }}"%"{{ active_directory_info.domain_join_password }}"
  register: "domain_joined"
  notify:
    - restart ctdb
  when: not domain_joined_check.stat.exists

- name: join_domain | marking as domain joined
  file:
    path: "{{ shared_storage_mountpoint }}/fsgw/.domain_joined"
    state: touch
    owner: root
    group: root
    mode: 0644
  when: domain_joined.changed

- name: join_domain | restarting ctdb #we do this again after joining the domain in order to get winbind started
  service:
    name: "ctdb"
    state: restarted
  when: domain_joined.changed

- name: join_domain | waiting for ctdb to restart
  wait_for:
    delay: 60  #we wait enough time for ctdb to startup samba services in order to join domain
    host: "{{ ansible_default_ipv4.address }}"
    port: 4379
  when: domain_joined.changed