---
# Install packages
- include: install_redhat_samba.yml
  tags:
  - packages

- include: configure_cephfs_backend.yml
  when: 
   - backend_fs == 'cephfs'
  
# Configure samba + winbind
- include: configure_samba.yml
  when:
    - samba_server | bool

# Configure CTDB
#- include: configure_ctdb.yml
#  when:
#    - samba_cluster == 'true'
