devices:
  - /dev/sdc
  - /dev/sdd
  - /dev/sdb
  - /dev/sda
  - /dev/sdg
  - /dev/sdh
  - /dev/sdf
  - /dev/sde
  - /dev/sdk
  - /dev/sdl

lvm_volumes:
  - data: /dev/1-1
  - data: /dev/1-2
  - data: /dev/1-3
  - data: /dev/1-4
  - data: /dev/1-5
  - data: /dev/1-6
  - data: /dev/1-7
  - data: /dev/1-8
  - data: /dev/1-9
  - data: /dev/1-10
