---
- name: config_samba | disabling samba service
  service:
    name: "smb"
    enabled: no
    state: stopped
  notify:
    - restart ctdb

- name: config_samba | configuring samba {{ ctdb_samba_config }}
  template:
    src: "etc/samba/smb.conf.j2"
    dest: "/etc/samba/smb.conf"
    owner: root
    group: root
    mode: 0644
    backup: "{{ ctdb_backup_configs }}"
  register: "samba_reconfigured"

- name: config_samba | configuring nssswitch
  template:
    src: "etc/nsswitch.conf.j2"
    dest: "/etc/nsswitch.conf"
    owner: root
    group: root
    mode: 0644
    backup: "{{ ctdb_backup_configs }}"

- name: config_samba | configuring kerberos
  template:
    src: "etc/krb5.conf.j2"
    dest: "/etc/krb5.conf"
    owner: root
    group: root
    mode: 0644
    backup: "{{ ctdb_backup_configs }}"

- name: config_samba | restarting ctdb (if samba reconfigured)  #we need to do this here before proceeding in order for Domain permissions and such to be assigned in later tasks.
  service:
    name: "ctdb"
    state: restarted
  register: "samba_ctdb_restarted"
  when: samba_reconfigured.changed

- name: config_samba | waiting for ctdb to restart
  wait_for:
    delay: 60  #we wait enough time for ctdb to startup samba services in order to continue
    host: "{{ ansible_default_ipv4.address }}"
    port: 4379
  when: samba_ctdb_restarted.changed
