---
- name: config_ctdb | ensuring {{ ctdb_lock_directory }} exists
  file:
    path: "{{ ctdb_lock_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0644
  when: not ctdb_rados_locking | bool

- name: config_ctdb | Check if {{ ctdb_lockfile }} exists
  stat:
    path: "{{ ctdb_lockfile }}"
  register: ctdb_lockfile_check
  when: not ctdb_rados_locking | bool

- name: config_ctdb | create empty lockfile {{ ctdb_lockfile }} if it doesnt exist
  file:
    path: "{{ ctdb_lockfile }}"
    state: touch
    owner: root
    group: root
    mode: 0774
  when: ctdb_lockfile_check.stat.exists == False

- name: config_ctdb | enabling ctdb service
  service:
    name: "ctdb"
    enabled: yes

- name: config_ctdb | configuring ctdb service
  template:
    src: "etc/ctdb/ctdbd.conf.j2"
    dest: "/etc/ctdb/ctdbd.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ctdb

- name: config_ctdb | configuring ctdb public_addresses
  template:
    src: "etc/ctdb/public_addresses.j2"
    dest: "{{ ctdb_public_addresses_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ctdb

- name: config_ctdb | configuring ctdb nodes
  template:
    src: "etc/ctdb/nodes.j2"
    dest: "/etc/ctdb/nodes"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ctdb
