---
- name: config_samba | configuring smb.conf
  template:
    src: etc/samba/smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: "root"
    group: "root"
    mode: 0644
  register: "samba_reconfigured"

- name: config_samba | configuring nssswitch.conf
  template:
    src: "etc/nsswitch.conf.j2"
    dest: "/etc/nsswitch.conf"
    owner: root
    group: root
    mode: 0644
  when:
    - domain_member | bool

- name: config_samba | configuring krb5.conf
  template:
    src: "etc/krb5.conf.j2"
    dest: "/etc/krb5.conf"
    owner: root
    group: root
    mode: 0644
  when:
    - domain_member | bool
